server:
  port: 4000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall-test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

jwt:
  header: Authorization
  header-prefix: "Bearer "
  base64-access-secret: "your-access-secret"
  base64-refresh-secret: "your-refresh-secret"
  # access-token is valid 24 hours
  access-token-validity-in-seconds: 86400
  # refresh-token is valid 30 days
  refresh-token-validity-in-seconds: 2592000

logging:
  level:
    online.ahayujie.mall: debug
